/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package etm;

import funcionarios.Funcionario;
import funcionarios.FuncionarioAdministrativo;
import funcionarios.GerenteLocal;
import funcionarios.GerenteRegional;
import funcionarios.GestorDeFrota;
import java.util.ArrayList;
import usuarios.Usuario;

/**
 *
 * @author Felipe Macedo
 */
public class Login extends javax.swing.JFrame {

    ArrayList<Usuario> usuarios;
    ETM etm;
    public Login() {
        initComponents();
        usuarios = new ArrayList();
        etm = new ETM("A","12");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        Login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        Login_CT_usuario = new javax.swing.JTextField();
        Login_CS_senha = new javax.swing.JPasswordField();
        Login_BT_login = new javax.swing.JButton();
        Longin_BT_limpar = new javax.swing.JButton();
        Login_CB_tipoFuncionario = new javax.swing.JComboBox();
        Cadastrar = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Cadastrar_CT_usuario = new javax.swing.JTextField();
        Cadastrar_CT_nome = new javax.swing.JTextField();
        Cadastrar_CTF_cpf = new javax.swing.JFormattedTextField();
        Cadastrar_CS_senha = new javax.swing.JPasswordField();
        Cadastrar_BT_cadastrar = new javax.swing.JButton();
        Cadastrar_BT_limpar = new javax.swing.JButton();
        Cadastrar_CB_tipoFuncionario = new javax.swing.JComboBox();

        jLabel3.setText("jLabel3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("USUÁRIO:");

        jLabel2.setText("SENHA:");

        Login_BT_login.setText("Login");
        Login_BT_login.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Login_BT_loginActionPerformed(evt);
            }
        });

        Longin_BT_limpar.setText("Limpar");

        Login_CB_tipoFuncionario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "GERENTE LOCAL", "GERENTE REGIONAL", "GESTOR DE FROTA" }));

        javax.swing.GroupLayout LoginLayout = new javax.swing.GroupLayout(Login);
        Login.setLayout(LoginLayout);
        LoginLayout.setHorizontalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(LoginLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Login_BT_login)
                    .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(LoginLayout.createSequentialGroup()
                            .addComponent(jLabel1)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(Login_CT_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(LoginLayout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(Login_CS_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(74, 74, 74)
                        .addComponent(Login_CB_tipoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(Longin_BT_limpar)))
                .addContainerGap(86, Short.MAX_VALUE))
        );
        LoginLayout.setVerticalGroup(
            LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, LoginLayout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(Login_CT_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(Login_CS_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(LoginLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Login_CB_tipoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(72, 72, 72)
                .addGroup(LoginLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Login_BT_login)
                    .addComponent(Longin_BT_limpar))
                .addContainerGap(83, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Login", Login);

        jLabel4.setText("USUÁRIO:");

        jLabel5.setText("SENHA:");

        jLabel6.setText("NOME:");

        jLabel7.setText("CPF:");

        Cadastrar_BT_cadastrar.setText("Cadastrar");
        Cadastrar_BT_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Cadastrar_BT_cadastrarActionPerformed(evt);
            }
        });

        Cadastrar_BT_limpar.setText("Limpar");

        Cadastrar_CB_tipoFuncionario.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "GERENTE LOCAL", "GERENTE REGIONAL", "GESTOR DE FROTA" }));

        javax.swing.GroupLayout CadastrarLayout = new javax.swing.GroupLayout(Cadastrar);
        Cadastrar.setLayout(CadastrarLayout);
        CadastrarLayout.setHorizontalGroup(
            CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarLayout.createSequentialGroup()
                .addGroup(CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastrarLayout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addComponent(Cadastrar_BT_cadastrar)
                        .addGap(18, 18, 18)
                        .addComponent(Cadastrar_BT_limpar))
                    .addGroup(CadastrarLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel7)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(CadastrarLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastrarLayout.createSequentialGroup()
                        .addComponent(jLabel6)
                        .addGap(148, 421, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastrarLayout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addGroup(CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(Cadastrar_CT_nome, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(Cadastrar_CTF_cpf))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(CadastrarLayout.createSequentialGroup()
                        .addGroup(CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastrarLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(26, 26, 26)
                                .addComponent(Cadastrar_CS_senha, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CadastrarLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Cadastrar_CT_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Cadastrar_CB_tipoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(43, 43, 43))))
        );
        CadastrarLayout.setVerticalGroup(
            CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastrarLayout.createSequentialGroup()
                .addGroup(CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(Cadastrar_CT_nome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Cadastrar_CTF_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Cadastrar_CB_tipoFuncionario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(CadastrarLayout.createSequentialGroup()
                        .addGroup(CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(Cadastrar_CT_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(Cadastrar_CS_senha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(64, 64, 64)
                .addGroup(CadastrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Cadastrar_BT_cadastrar)
                    .addComponent(Cadastrar_BT_limpar))
                .addContainerGap(74, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Cadastrar", Cadastrar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    public void setEtm(ETM etm){
        this.etm = etm;
    }
    
    public void setUsuarios(ArrayList usuarios){
        this.usuarios = usuarios;
    }
    
    private void Cadastrar_BT_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Cadastrar_BT_cadastrarActionPerformed
        String tipoFuncionario;
        String nickName;
        String senha;
        String nome;
        String cpf;
        Funcionario fun = null;
        tipoFuncionario = Cadastrar_CB_tipoFuncionario.getSelectedItem().toString();
        nickName = Cadastrar_CT_usuario.getText();
        senha = String.valueOf(Cadastrar_CS_senha.getPassword());
        nome = Cadastrar_CT_nome.getText();
        cpf = Cadastrar_CTF_cpf.getText();
        
        switch(tipoFuncionario){
            case "GERENTE REGIONAL":
                fun = new GerenteRegional(nome, cpf, etm);
                break;
            case "GERENTE LOCAL":
                fun = new GerenteLocal(nome, cpf, etm);
                break;
            case "GESTOR DE FROTA":
                fun = new GestorDeFrota(nome, cpf, etm);
                break;
        }
        if(fun != null){
            Usuario usuario = new Usuario(nickName, senha, fun);
            if(!usuarios.contains(usuario)){usuarios.add(usuario);}
        }
        
    }//GEN-LAST:event_Cadastrar_BT_cadastrarActionPerformed

    private void Login_BT_loginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Login_BT_loginActionPerformed
        String nickName;
        String senha;
        String tipoFuncionario;
        Usuario usuario;
        Usuario usuarioControle;
        
        nickName = Login_CT_usuario.getText();
        senha = String.valueOf(Login_CS_senha.getPassword());
        tipoFuncionario = Login_CB_tipoFuncionario.getSelectedItem().toString();
        usuario = new Usuario(nickName,senha);
        usuarioControle = usuarios.get(usuarios.indexOf(usuario));
        
        if(usuarios.contains(usuario)&&usuarioControle.getNickName().equals(nickName)&&usuarioControle.getSenha().equals(senha)){
            switch(tipoFuncionario){
                case "GERENTE REGIONAL":
                    break;
                case "GERENTE LOCAL":
                    break;
                case "GESTOR DE FROTA":
                    TelaGestorDeFrota tela = new TelaGestorDeFrota();
                    tela.setEtm(etm);
                    tela.setUsuarios(usuarios);
                    tela.setUsuario(usuario);
                    tela.setVisible(true);
                    this.dispose();
                    break;
            }
        }
        
    }//GEN-LAST:event_Login_BT_loginActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Cadastrar;
    private javax.swing.JButton Cadastrar_BT_cadastrar;
    private javax.swing.JButton Cadastrar_BT_limpar;
    private javax.swing.JComboBox Cadastrar_CB_tipoFuncionario;
    private javax.swing.JPasswordField Cadastrar_CS_senha;
    private javax.swing.JFormattedTextField Cadastrar_CTF_cpf;
    private javax.swing.JTextField Cadastrar_CT_nome;
    private javax.swing.JTextField Cadastrar_CT_usuario;
    private javax.swing.JPanel Login;
    private javax.swing.JButton Login_BT_login;
    private javax.swing.JComboBox Login_CB_tipoFuncionario;
    private javax.swing.JPasswordField Login_CS_senha;
    private javax.swing.JTextField Login_CT_usuario;
    private javax.swing.JButton Longin_BT_limpar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
