package etm;

import auxiliar.Rota;
import funcionarios.Funcionario;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import usuarios.Usuario;
import veiculos.Onibus;
import veiculos.Veiculo;

public class TelaGestorDeFrota extends javax.swing.JFrame {

    ETM etm;
    ArrayList<Usuario> usuarios;
    Usuario usuario;
    public TelaGestorDeFrota() {
        initComponents();
        etm = new ETM();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @param etm
     */
    
    
    
    public void setEtm(ETM etm){
        this.etm = etm;
    }
    
    public final void setPerfil(){
        Funcionario f = usuario.getFuncionario();
        Perfil_CT_usuario.setText(usuario.getNickName());
        if(usuario.getFuncionario()  != null){
            Perfil_CT_salario.setText(String.valueOf(f.getSalario()));
            Perfil_CT_cargaHoraria.setText(String.valueOf(f.getCargaHoraria()));
        }
        
    }
    
    public void setUsuarios(ArrayList<Usuario> usuarios) {
        this.usuarios = usuarios;
    }
    
    public void setUsuario(Usuario usuario){
        this.usuario = usuario;
    }
    
    public ArrayList<Usuario> getUsuarios() {
        return usuarios;
    }
    
    public void exibirMsg(String msg){
        JOptionPane.showMessageDialog(rootPane, msg);
    }
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup2 = new javax.swing.ButtonGroup();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        CadastrarVeiculo_P = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        CadasVei_CT_capacidade = new javax.swing.JTextField();
        CadasVei_CT_autonomia = new javax.swing.JTextField();
        CadasVei_CB_tipoDeRota = new javax.swing.JComboBox();
        CadasVei_CB_tipoDeCobranca = new javax.swing.JComboBox();
        CadasVei_CB_status = new javax.swing.JComboBox();
        CadasVei_CB_rotas = new javax.swing.JComboBox();
        CadasVei_CB_tipoCombustivel = new javax.swing.JComboBox();
        CadasVei_CB_tipoDeVeiculo = new javax.swing.JComboBox();
        CadasVei_BT_cadastrar = new javax.swing.JButton();
        CadasVei_BT_limpar = new javax.swing.JButton();
        CadasVei_P_remover = new javax.swing.JButton();
        CadasVei_P_atualizar = new javax.swing.JButton();
        CadasVei_P_buscar = new javax.swing.JButton();
        CadasVei_P_placa = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        CadasVei_CT_placa = new javax.swing.JTextField();
        CadasVei_P_id = new javax.swing.JPanel();
        CadasVei_CT_id = new javax.swing.JTextField();
        jLabel32 = new javax.swing.JLabel();
        CadastrarParada_P = new javax.swing.JPanel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        CadasParada_CT_endereco = new javax.swing.JTextField();
        CadasParada_CT_latitude = new javax.swing.JTextField();
        CadasParada_CT_longitude = new javax.swing.JTextField();
        CadasParada_CT_id = new javax.swing.JTextField();
        CadasParada_BT_cadastrar = new javax.swing.JButton();
        CadasParada_BT_limpar = new javax.swing.JButton();
        CadasParada_BT_atualizar = new javax.swing.JButton();
        CadasParada_BT_remover = new javax.swing.JButton();
        CadasParada_BT_buscar = new javax.swing.JButton();
        Alocar_P = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        CadasEmVe_CT_cpf = new javax.swing.JTextField();
        CadasEmVe_BT_veiculoId = new javax.swing.JTextField();
        CadasEmVe_CT_rotaId = new javax.swing.JTextField();
        CadasEmVe_BT_buscar = new javax.swing.JButton();
        CadasEmVe_BT_cadastrar = new javax.swing.JButton();
        CadasEmVe_BT_descadastrar = new javax.swing.JButton();
        CadasEmVe_BT_atualizar = new javax.swing.JButton();
        CadasEmVe_BT_limpar = new javax.swing.JButton();
        jComboBox1 = new javax.swing.JComboBox();
        CadastrarRota_P = new javax.swing.JPanel();
        jLabel22 = new javax.swing.JLabel();
        IdParada = new javax.swing.JLabel();
        CadasRota_CT_idParada = new javax.swing.JTextField();
        Relatorios_P = new javax.swing.JPanel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        Relatorios_BT_balanco = new javax.swing.JButton();
        Relatorios_BT_mostrarRelatorio = new javax.swing.JButton();
        Relatorios_BT_limpar = new javax.swing.JButton();
        Relatorios_CT_sexo = new javax.swing.JTextField();
        Relatorios_CT_idade = new javax.swing.JTextField();
        Relatorios_CT_renda = new javax.swing.JTextField();
        Relatorios_RB_veiculo = new javax.swing.JRadioButton();
        Relatorios_RB_funcionario = new javax.swing.JRadioButton();
        Relatorios_CB_tipoDeVeiculos = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        Relatorios_PT_info = new javax.swing.JTextPane();
        BuscarRelatorios_P = new javax.swing.JPanel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        RelatoriosPorPe_CTF_dataInicial = new javax.swing.JFormattedTextField();
        RelatoriosPorPe_CTF_dataFinal = new javax.swing.JFormattedTextField();
        RelatoriosPorPe_BT_mostraRelatorio = new javax.swing.JButton();
        RelatoriosPorPe_BT_limpar = new javax.swing.JButton();
        RelatoriosPorPe_RB_veiculo = new javax.swing.JRadioButton();
        RelatoriosPorPe_RB_funcionario = new javax.swing.JRadioButton();
        RelatoriosPorPe_CB_tipoDeVeiculo = new javax.swing.JComboBox();
        jScrollPane4 = new javax.swing.JScrollPane();
        RelatoriosPorPe_AT_info = new javax.swing.JTextArea();
        Perfil_P = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        Perfil_CT_usuario = new javax.swing.JTextField();
        Perfil_CT_cargaHoraria = new javax.swing.JTextField();
        Perfil_CT_salario = new javax.swing.JTextField();
        Pefil_CS_senhaAntiga = new javax.swing.JPasswordField();
        Pefil_CS_senhaNova = new javax.swing.JPasswordField();
        Pefil_BT_atualizar = new javax.swing.JButton();
        Pefil_BT_limpar = new javax.swing.JButton();
        Pefil_BT_sair = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel3.setText("Status:");

        jLabel4.setText("Combustível:");

        jLabel5.setText("Capacidade:");

        jLabel6.setText("Custo por Km:");

        jLabel9.setText("Tipo de rota:");

        jLabel7.setText("Rotas:");

        jLabel8.setText("Tipo de Veículo:");

        jLabel10.setText("Tipo de cobrança:");

        CadasVei_CT_capacidade.setText("0");

        CadasVei_CT_autonomia.setText("0");

        CadasVei_CB_tipoDeRota.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "FLEXÍVEL", "FIXA" }));

        CadasVei_CB_tipoDeCobranca.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "MANUAL", "MISTA" }));

        CadasVei_CB_status.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "OPERACIONAL", "EM MANUTENÇÃO" }));
        CadasVei_CB_status.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadasVei_CB_statusActionPerformed(evt);
            }
        });

        CadasVei_CB_rotas.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-" }));

        CadasVei_CB_tipoCombustivel.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "GASOLINA", "DÍSEL", "ELETICIDADE", "GÁS" }));

        CadasVei_CB_tipoDeVeiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "VLT", "BRT", "VAN", "METRÔ", "ÔNIBUS", "MICRO-ÔNIBUS" }));
        CadasVei_CB_tipoDeVeiculo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadasVei_CB_tipoDeVeiculoActionPerformed(evt);
            }
        });

        CadasVei_BT_cadastrar.setText("Cadastrar");
        CadasVei_BT_cadastrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadasVei_BT_cadastrarActionPerformed(evt);
            }
        });

        CadasVei_BT_limpar.setText("Limpar");

        CadasVei_P_remover.setText("Remover");

        CadasVei_P_atualizar.setText("Atualizar");

        CadasVei_P_buscar.setText("Buscar");
        CadasVei_P_buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CadasVei_P_buscarActionPerformed(evt);
            }
        });

        CadasVei_P_placa.setVisible(false);
        CadasVei_P_placa.setName(""); // NOI18N

        jLabel11.setText("Placa:");

        javax.swing.GroupLayout CadasVei_P_placaLayout = new javax.swing.GroupLayout(CadasVei_P_placa);
        CadasVei_P_placa.setLayout(CadasVei_P_placaLayout);
        CadasVei_P_placaLayout.setHorizontalGroup(
            CadasVei_P_placaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadasVei_P_placaLayout.createSequentialGroup()
                .addContainerGap(11, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CadasVei_CT_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        CadasVei_P_placaLayout.setVerticalGroup(
            CadasVei_P_placaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadasVei_P_placaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadasVei_P_placaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadasVei_CT_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(20, 20, 20))
        );

        CadasVei_P_id.setVisible(false);

        jLabel32.setText("ID:");

        javax.swing.GroupLayout CadasVei_P_idLayout = new javax.swing.GroupLayout(CadasVei_P_id);
        CadasVei_P_id.setLayout(CadasVei_P_idLayout);
        CadasVei_P_idLayout.setHorizontalGroup(
            CadasVei_P_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadasVei_P_idLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel32, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(CadasVei_CT_id, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(8, 8, 8))
        );
        CadasVei_P_idLayout.setVerticalGroup(
            CadasVei_P_idLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel32)
            .addComponent(CadasVei_CT_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        javax.swing.GroupLayout CadastrarVeiculo_PLayout = new javax.swing.GroupLayout(CadastrarVeiculo_P);
        CadastrarVeiculo_P.setLayout(CadastrarVeiculo_PLayout);
        CadastrarVeiculo_PLayout.setHorizontalGroup(
            CadastrarVeiculo_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarVeiculo_PLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastrarVeiculo_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastrarVeiculo_PLayout.createSequentialGroup()
                        .addGroup(CadastrarVeiculo_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(CadasVei_P_atualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CadasVei_BT_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(CadastrarVeiculo_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CadasVei_P_buscar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CadasVei_P_remover, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(CadasVei_BT_limpar))
                    .addGroup(CadastrarVeiculo_PLayout.createSequentialGroup()
                        .addGroup(CadastrarVeiculo_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CadastrarVeiculo_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(CadastrarVeiculo_PLayout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addGap(18, 18, 18)
                                    .addComponent(CadasVei_CB_rotas, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(CadastrarVeiculo_PLayout.createSequentialGroup()
                                    .addGroup(CadastrarVeiculo_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel5)
                                        .addComponent(jLabel6)
                                        .addComponent(jLabel4))
                                    .addGap(18, 18, 18)
                                    .addGroup(CadastrarVeiculo_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(CadasVei_CT_autonomia)
                                        .addComponent(CadasVei_CT_capacidade)
                                        .addComponent(CadasVei_CB_tipoCombustivel, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addGroup(CadastrarVeiculo_PLayout.createSequentialGroup()
                                    .addComponent(jLabel3)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(CadasVei_CB_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(CadastrarVeiculo_PLayout.createSequentialGroup()
                                .addGap(8, 8, 8)
                                .addComponent(CadasVei_P_id, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(82, 82, 82)
                        .addGroup(CadastrarVeiculo_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(CadasVei_P_placa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(CadastrarVeiculo_PLayout.createSequentialGroup()
                                .addGroup(CadastrarVeiculo_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(CadastrarVeiculo_PLayout.createSequentialGroup()
                                        .addGroup(CadastrarVeiculo_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel9)
                                            .addComponent(jLabel8))
                                        .addGap(29, 29, 29))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastrarVeiculo_PLayout.createSequentialGroup()
                                        .addComponent(jLabel10)
                                        .addGap(18, 18, 18)))
                                .addGroup(CadastrarVeiculo_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(CadasVei_CB_tipoDeCobranca, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CadasVei_CB_tipoDeVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(CadasVei_CB_tipoDeRota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(138, Short.MAX_VALUE))
        );
        CadastrarVeiculo_PLayout.setVerticalGroup(
            CadastrarVeiculo_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarVeiculo_PLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(CadastrarVeiculo_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(CadastrarVeiculo_PLayout.createSequentialGroup()
                        .addGroup(CadastrarVeiculo_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel8)
                            .addComponent(CadasVei_CB_tipoDeVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CadastrarVeiculo_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(CadasVei_CB_tipoDeRota, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(CadastrarVeiculo_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CadasVei_CB_tipoDeCobranca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10))
                        .addGap(18, 18, 18))
                    .addGroup(CadastrarVeiculo_PLayout.createSequentialGroup()
                        .addComponent(CadasVei_P_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(17, 17, 17)
                        .addGroup(CadastrarVeiculo_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CadasVei_CB_status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CadastrarVeiculo_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(CadasVei_CB_tipoCombustivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(11, 11, 11)))
                .addGroup(CadastrarVeiculo_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastrarVeiculo_PLayout.createSequentialGroup()
                        .addGroup(CadastrarVeiculo_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(CadasVei_CT_capacidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(CadastrarVeiculo_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(CadasVei_CT_autonomia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(CadasVei_P_placa, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(CadastrarVeiculo_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(CadasVei_CB_rotas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                .addGroup(CadastrarVeiculo_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadasVei_BT_cadastrar)
                    .addComponent(CadasVei_BT_limpar)
                    .addComponent(CadasVei_P_buscar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastrarVeiculo_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadasVei_P_atualizar)
                    .addComponent(CadasVei_P_remover))
                .addGap(25, 25, 25))
        );

        jTabbedPane1.addTab("Cadastrar veículo", CadastrarVeiculo_P);

        jLabel13.setText("Endereço:");

        jLabel14.setText("Latitude:");

        jLabel15.setText("Longitude:");

        jLabel33.setText("ID:");

        CadasParada_BT_cadastrar.setText("Cadastrar");

        CadasParada_BT_limpar.setText("Limpar");

        CadasParada_BT_atualizar.setText("Atualizar");

        CadasParada_BT_remover.setText("Remover");

        CadasParada_BT_buscar.setText("Buscar");

        javax.swing.GroupLayout CadastrarParada_PLayout = new javax.swing.GroupLayout(CadastrarParada_P);
        CadastrarParada_P.setLayout(CadastrarParada_PLayout);
        CadastrarParada_PLayout.setHorizontalGroup(
            CadastrarParada_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarParada_PLayout.createSequentialGroup()
                .addGroup(CadastrarParada_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastrarParada_PLayout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addGroup(CadastrarParada_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CadasParada_BT_cadastrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(CadasParada_BT_atualizar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(CadastrarParada_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(CadastrarParada_PLayout.createSequentialGroup()
                                .addComponent(CadasParada_BT_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(17, 17, 17)
                                .addComponent(CadasParada_BT_buscar))
                            .addComponent(CadasParada_BT_remover)))
                    .addGroup(CadastrarParada_PLayout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(CadastrarParada_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(CadastrarParada_PLayout.createSequentialGroup()
                                .addComponent(jLabel15)
                                .addGap(18, 18, 18)
                                .addComponent(CadasParada_CT_longitude, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(CadastrarParada_PLayout.createSequentialGroup()
                                .addGroup(CadastrarParada_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, CadastrarParada_PLayout.createSequentialGroup()
                                        .addGroup(CadastrarParada_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel13)
                                            .addComponent(jLabel14))
                                        .addGap(18, 18, 18))
                                    .addGroup(CadastrarParada_PLayout.createSequentialGroup()
                                        .addComponent(jLabel33)
                                        .addGap(27, 27, 27)))
                                .addGroup(CadastrarParada_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(CadasParada_CT_endereco, javax.swing.GroupLayout.DEFAULT_SIZE, 69, Short.MAX_VALUE)
                                    .addComponent(CadasParada_CT_latitude)
                                    .addComponent(CadasParada_CT_id))))))
                .addContainerGap(331, Short.MAX_VALUE))
        );
        CadastrarParada_PLayout.setVerticalGroup(
            CadastrarParada_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarParada_PLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(CadastrarParada_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(CadasParada_CT_endereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastrarParada_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel33)
                    .addComponent(CadasParada_CT_id, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastrarParada_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(CadasParada_CT_latitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(CadastrarParada_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(CadasParada_CT_longitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 187, Short.MAX_VALUE)
                .addGroup(CadastrarParada_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadasParada_BT_cadastrar)
                    .addComponent(CadasParada_BT_buscar)
                    .addComponent(CadasParada_BT_limpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(CadastrarParada_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadasParada_BT_atualizar)
                    .addComponent(CadasParada_BT_remover))
                .addGap(20, 20, 20))
        );

        jTabbedPane1.addTab("Cadastrar Parada", CadastrarParada_P);

        jLabel1.setText("CPF:");

        jLabel2.setText("Veículo id:");

        jLabel12.setText("Rota id:");

        CadasEmVe_BT_buscar.setText("Buscar");

        CadasEmVe_BT_cadastrar.setText("Cadastrar");

        CadasEmVe_BT_descadastrar.setText("Descadastrar");

        CadasEmVe_BT_atualizar.setText("Atualizar");

        CadasEmVe_BT_limpar.setText("Limpar");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "ROTA", "VEÍCULO" }));

        jLabel22.setText("Parada");

        IdParada.setText("ID:");

        javax.swing.GroupLayout CadastrarRota_PLayout = new javax.swing.GroupLayout(CadastrarRota_P);
        CadastrarRota_P.setLayout(CadastrarRota_PLayout);
        CadastrarRota_PLayout.setHorizontalGroup(
            CadastrarRota_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarRota_PLayout.createSequentialGroup()
                .addGroup(CadastrarRota_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(CadastrarRota_PLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(IdParada)
                        .addGap(18, 18, 18)
                        .addComponent(CadasRota_CT_idParada, javax.swing.GroupLayout.PREFERRED_SIZE, 56, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(CadastrarRota_PLayout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(jLabel22)))
                .addGap(0, 17, Short.MAX_VALUE))
        );
        CadastrarRota_PLayout.setVerticalGroup(
            CadastrarRota_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(CadastrarRota_PLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel22)
                .addGap(18, 18, 18)
                .addGroup(CadastrarRota_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(IdParada)
                    .addComponent(CadasRota_CT_idParada, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout Alocar_PLayout = new javax.swing.GroupLayout(Alocar_P);
        Alocar_P.setLayout(Alocar_PLayout);
        Alocar_PLayout.setHorizontalGroup(
            Alocar_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Alocar_PLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Alocar_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Alocar_PLayout.createSequentialGroup()
                        .addGroup(Alocar_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel12))
                        .addGap(18, 18, 18)
                        .addGroup(Alocar_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(CadasEmVe_BT_veiculoId, javax.swing.GroupLayout.DEFAULT_SIZE, 61, Short.MAX_VALUE)
                            .addComponent(CadasEmVe_CT_rotaId)))
                    .addGroup(Alocar_PLayout.createSequentialGroup()
                        .addComponent(CadasEmVe_BT_atualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CadasEmVe_BT_limpar, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Alocar_PLayout.createSequentialGroup()
                        .addGroup(Alocar_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Alocar_PLayout.createSequentialGroup()
                                .addComponent(CadasEmVe_BT_buscar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(CadasEmVe_BT_cadastrar))
                            .addGroup(Alocar_PLayout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(CadasEmVe_CT_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(Alocar_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CadasEmVe_BT_descadastrar)))
                    .addComponent(CadastrarRota_P, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(342, Short.MAX_VALUE))
        );
        Alocar_PLayout.setVerticalGroup(
            Alocar_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Alocar_PLayout.createSequentialGroup()
                .addGap(54, 54, 54)
                .addGroup(Alocar_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(CadasEmVe_CT_cpf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(Alocar_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(CadasEmVe_BT_veiculoId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Alocar_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(CadasEmVe_CT_rotaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(CadastrarRota_P, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 69, Short.MAX_VALUE)
                .addGroup(Alocar_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadasEmVe_BT_buscar)
                    .addComponent(CadasEmVe_BT_cadastrar)
                    .addComponent(CadasEmVe_BT_descadastrar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(Alocar_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CadasEmVe_BT_atualizar)
                    .addComponent(CadasEmVe_BT_limpar))
                .addGap(29, 29, 29))
        );

        jTabbedPane1.addTab("Alocar ", Alocar_P);

        jLabel23.setText("Sexo:");

        jLabel24.setText("Tipo de veículo:");

        jLabel25.setText("Idade:");

        jLabel26.setText("Renda:");

        Relatorios_BT_balanco.setText("Balanço");

        Relatorios_BT_mostrarRelatorio.setText("Mostra Relatório");

        Relatorios_BT_limpar.setText("Limpar");

        buttonGroup2.add(Relatorios_RB_veiculo);
        Relatorios_RB_veiculo.setText("Veículo ");

        buttonGroup2.add(Relatorios_RB_funcionario);
        Relatorios_RB_funcionario.setText("Funcionário");

        Relatorios_CB_tipoDeVeiculos.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "ÔNIBUS", "BRT", "MICRO-ÔNIBUS", "METRÔ", "VLT" }));

        jScrollPane1.setViewportView(Relatorios_PT_info);

        javax.swing.GroupLayout Relatorios_PLayout = new javax.swing.GroupLayout(Relatorios_P);
        Relatorios_P.setLayout(Relatorios_PLayout);
        Relatorios_PLayout.setHorizontalGroup(
            Relatorios_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Relatorios_PLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(Relatorios_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(Relatorios_PLayout.createSequentialGroup()
                        .addComponent(jLabel24)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Relatorios_CB_tipoDeVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(Relatorios_PLayout.createSequentialGroup()
                        .addGroup(Relatorios_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Relatorios_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Relatorios_PLayout.createSequentialGroup()
                                    .addComponent(jLabel23)
                                    .addGap(18, 18, 18))
                                .addGroup(Relatorios_PLayout.createSequentialGroup()
                                    .addComponent(jLabel25)
                                    .addGap(14, 14, 14)))
                            .addGroup(Relatorios_PLayout.createSequentialGroup()
                                .addComponent(jLabel26)
                                .addGap(11, 11, 11)))
                        .addGroup(Relatorios_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(Relatorios_CT_renda, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                            .addComponent(Relatorios_CT_idade, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Relatorios_CT_sexo, javax.swing.GroupLayout.Alignment.LEADING)))
                    .addGroup(Relatorios_PLayout.createSequentialGroup()
                        .addComponent(Relatorios_RB_veiculo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Relatorios_RB_funcionario))
                    .addGroup(Relatorios_PLayout.createSequentialGroup()
                        .addComponent(Relatorios_BT_balanco)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Relatorios_BT_mostrarRelatorio))
                    .addComponent(Relatorios_BT_limpar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 387, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(22, 22, 22))
        );
        Relatorios_PLayout.setVerticalGroup(
            Relatorios_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Relatorios_PLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1)
                .addGap(26, 26, 26))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, Relatorios_PLayout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(Relatorios_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Relatorios_RB_veiculo)
                    .addComponent(Relatorios_RB_funcionario))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 107, Short.MAX_VALUE)
                .addGroup(Relatorios_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel24)
                    .addComponent(Relatorios_CB_tipoDeVeiculos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Relatorios_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel23)
                    .addComponent(Relatorios_CT_sexo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Relatorios_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel25)
                    .addComponent(Relatorios_CT_idade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(Relatorios_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel26)
                    .addComponent(Relatorios_CT_renda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Relatorios_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Relatorios_BT_balanco)
                    .addComponent(Relatorios_BT_mostrarRelatorio))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Relatorios_BT_limpar)
                .addGap(21, 21, 21))
        );

        jTabbedPane1.addTab("Relatórios", Relatorios_P);

        jLabel27.setText("Data de início:");

        jLabel28.setText("Data de fim:");

        jLabel29.setText("Tipo de veículo:");

        RelatoriosPorPe_CTF_dataFinal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatoriosPorPe_CTF_dataFinalActionPerformed(evt);
            }
        });

        RelatoriosPorPe_BT_mostraRelatorio.setText("Mostra Relatório");
        RelatoriosPorPe_BT_mostraRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RelatoriosPorPe_BT_mostraRelatorioActionPerformed(evt);
            }
        });

        RelatoriosPorPe_BT_limpar.setText("Limpar");

        buttonGroup2.add(RelatoriosPorPe_RB_veiculo);
        RelatoriosPorPe_RB_veiculo.setText("Veículo ");

        buttonGroup2.add(RelatoriosPorPe_RB_funcionario);
        RelatoriosPorPe_RB_funcionario.setText("Funcionário");

        RelatoriosPorPe_CB_tipoDeVeiculo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "-", "ÔNIBUS", "BRT", "MICRO-ÔNIBUS", "METRÔ", "VLT" }));

        RelatoriosPorPe_AT_info.setColumns(20);
        RelatoriosPorPe_AT_info.setRows(5);
        jScrollPane4.setViewportView(RelatoriosPorPe_AT_info);

        javax.swing.GroupLayout BuscarRelatorios_PLayout = new javax.swing.GroupLayout(BuscarRelatorios_P);
        BuscarRelatorios_P.setLayout(BuscarRelatorios_PLayout);
        BuscarRelatorios_PLayout.setHorizontalGroup(
            BuscarRelatorios_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarRelatorios_PLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(BuscarRelatorios_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BuscarRelatorios_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(BuscarRelatorios_PLayout.createSequentialGroup()
                            .addComponent(RelatoriosPorPe_BT_mostraRelatorio)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(RelatoriosPorPe_BT_limpar))
                        .addGroup(BuscarRelatorios_PLayout.createSequentialGroup()
                            .addComponent(jLabel29)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addComponent(RelatoriosPorPe_CB_tipoDeVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(BuscarRelatorios_PLayout.createSequentialGroup()
                            .addGroup(BuscarRelatorios_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel28)
                                .addComponent(jLabel27))
                            .addGap(18, 18, 18)
                            .addGroup(BuscarRelatorios_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(RelatoriosPorPe_CTF_dataInicial, javax.swing.GroupLayout.DEFAULT_SIZE, 109, Short.MAX_VALUE)
                                .addComponent(RelatoriosPorPe_CTF_dataFinal))))
                    .addGroup(BuscarRelatorios_PLayout.createSequentialGroup()
                        .addComponent(RelatoriosPorPe_RB_veiculo)
                        .addGap(14, 14, 14)
                        .addComponent(RelatoriosPorPe_RB_funcionario)))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 272, Short.MAX_VALUE)
                .addGap(116, 116, 116))
        );
        BuscarRelatorios_PLayout.setVerticalGroup(
            BuscarRelatorios_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BuscarRelatorios_PLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(BuscarRelatorios_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(BuscarRelatorios_PLayout.createSequentialGroup()
                        .addGroup(BuscarRelatorios_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RelatoriosPorPe_RB_veiculo)
                            .addComponent(RelatoriosPorPe_RB_funcionario))
                        .addGap(28, 28, 28)
                        .addGroup(BuscarRelatorios_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel29)
                            .addComponent(RelatoriosPorPe_CB_tipoDeVeiculo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(BuscarRelatorios_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RelatoriosPorPe_CTF_dataInicial, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel27))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(BuscarRelatorios_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RelatoriosPorPe_CTF_dataFinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel28))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 207, Short.MAX_VALUE)
                        .addGroup(BuscarRelatorios_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(RelatoriosPorPe_BT_mostraRelatorio)
                            .addComponent(RelatoriosPorPe_BT_limpar))))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Relatórios por período", BuscarRelatorios_P);

        Perfil_P.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                Perfil_PMouseClicked(evt);
            }
        });

        jLabel16.setText("Usuário:");

        jLabel17.setText("Senha antiga:");

        jLabel18.setText("Senha nova:");

        jLabel19.setText("Salário:");

        jLabel20.setText("Carga horária:");

        Perfil_CT_usuario.setEditable(false);

        Perfil_CT_cargaHoraria.setEditable(false);

        Perfil_CT_salario.setEditable(false);

        Pefil_BT_atualizar.setText("Atualizar");

        Pefil_BT_limpar.setText("Limpar");
        Pefil_BT_limpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pefil_BT_limparActionPerformed(evt);
            }
        });

        Pefil_BT_sair.setText("Sair");
        Pefil_BT_sair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Pefil_BT_sairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Perfil_PLayout = new javax.swing.GroupLayout(Perfil_P);
        Perfil_P.setLayout(Perfil_PLayout);
        Perfil_PLayout.setHorizontalGroup(
            Perfil_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Perfil_PLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addGroup(Perfil_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(Perfil_PLayout.createSequentialGroup()
                        .addComponent(Pefil_BT_atualizar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Pefil_BT_limpar)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Pefil_BT_sair))
                    .addGroup(Perfil_PLayout.createSequentialGroup()
                        .addComponent(jLabel16)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(Perfil_CT_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(128, 128, 128)
                        .addGroup(Perfil_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(Perfil_PLayout.createSequentialGroup()
                                .addComponent(jLabel20)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Perfil_CT_cargaHoraria))
                            .addGroup(Perfil_PLayout.createSequentialGroup()
                                .addComponent(jLabel19)
                                .addGap(18, 18, 18)
                                .addComponent(Perfil_CT_salario, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(Perfil_PLayout.createSequentialGroup()
                        .addGroup(Perfil_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel17)
                            .addComponent(jLabel18))
                        .addGroup(Perfil_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(Perfil_PLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Pefil_CS_senhaNova))
                            .addGroup(Perfil_PLayout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(Pefil_CS_senhaAntiga)))
                        .addGap(176, 176, 176)))
                .addContainerGap(203, Short.MAX_VALUE))
        );
        Perfil_PLayout.setVerticalGroup(
            Perfil_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(Perfil_PLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(Perfil_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel16)
                    .addComponent(Perfil_CT_usuario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel19)
                    .addComponent(Perfil_CT_salario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(Perfil_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel17)
                    .addComponent(Pefil_CS_senhaAntiga, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel20)
                    .addComponent(Perfil_CT_cargaHoraria, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(Perfil_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel18)
                    .addComponent(Pefil_CS_senhaNova, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 211, Short.MAX_VALUE)
                .addGroup(Perfil_PLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Pefil_BT_atualizar)
                    .addComponent(Pefil_BT_limpar)
                    .addComponent(Pefil_BT_sair))
                .addGap(39, 39, 39))
        );

        jTabbedPane1.addTab("Perfil", Perfil_P);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RelatoriosPorPe_CTF_dataFinalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatoriosPorPe_CTF_dataFinalActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RelatoriosPorPe_CTF_dataFinalActionPerformed

    private void RelatoriosPorPe_BT_mostraRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RelatoriosPorPe_BT_mostraRelatorioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_RelatoriosPorPe_BT_mostraRelatorioActionPerformed

    private void CadasVei_BT_cadastrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadasVei_BT_cadastrarActionPerformed
        String status;
        String tipoDeCombustivel;
        String tipoDeVeiculo;
        String tipoDeRota;
        String tipoDeCobranca;
        String placa;
        int capacidade;
        float autonomia;

        Veiculo nVeiculo=null;
        status = CadasVei_CB_status.getSelectedItem().toString();
        tipoDeCombustivel = CadasVei_CB_tipoCombustivel.getSelectedItem().toString();
        tipoDeRota = CadasVei_CB_tipoDeRota.getSelectedItem().toString();
        tipoDeVeiculo = CadasVei_CB_tipoDeVeiculo.getSelectedItem().toString();
        tipoDeCobranca = CadasVei_CB_tipoDeCobranca.getSelectedItem().toString();
        placa = CadasVei_CT_placa.getText();
        capacidade = Integer.parseInt(CadasVei_CT_capacidade.getText());
        autonomia = Float.parseFloat(CadasVei_CT_autonomia.getText());

        switch(tipoDeVeiculo){
            case "VLT":
                
                break;
            case "BRT":
                break;
            case "VAN":
                break;
            case "METRÔ":
                break;
            case "ÔNIBUS":
                nVeiculo = new Onibus(placa,"",status,tipoDeCombustivel,tipoDeRota,tipoDeCobranca,capacidade,autonomia);
                break;
            case "MICRO-ÔNIBUS":
        }
        if(nVeiculo != null){
            etm.cadastrarVeiculo(nVeiculo);
            CadasVei_P_id.setVisible(true);
            CadasVei_CT_id.setText(nVeiculo.getId());
        }
        
    }//GEN-LAST:event_CadasVei_BT_cadastrarActionPerformed

    private void CadasVei_CB_statusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadasVei_CB_statusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CadasVei_CB_statusActionPerformed

    private void CadasVei_CB_tipoDeVeiculoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadasVei_CB_tipoDeVeiculoActionPerformed
        String tipoDeVeiculo;
        tipoDeVeiculo = CadasVei_CB_tipoDeVeiculo.getSelectedItem().toString();
        switch(tipoDeVeiculo){
            case "ÔNIBUS":case "MICRO-ÔNIBUS":
                CadasVei_P_placa.setVisible(true);
                break;
            default:
                CadasVei_P_placa.setVisible(false);
                break;
        }
    }//GEN-LAST:event_CadasVei_CB_tipoDeVeiculoActionPerformed

    private void Pefil_BT_limparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pefil_BT_limparActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_Pefil_BT_limparActionPerformed

    private void Pefil_BT_sairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Pefil_BT_sairActionPerformed
        Login telaLogin = new Login();
        telaLogin.setEtm(etm);
        telaLogin.setUsuarios(usuarios);
        telaLogin.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_Pefil_BT_sairActionPerformed

    private void Perfil_PMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_Perfil_PMouseClicked
       setPerfil();
    }//GEN-LAST:event_Perfil_PMouseClicked

    private void CadasVei_P_buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CadasVei_P_buscarActionPerformed
        Veiculo veiculo;
        String id;
        
        id = CadasVei_CT_id.getText();
        veiculo = etm.buscarVeiculo(id);
        if(veiculo != null){
            CadasVei_CB_status.setSelectedItem(veiculo.getStatus());
            CadasVei_CB_tipoCombustivel.setSelectedItem(veiculo.getCombustivel());
            CadasVei_CB_tipoDeRota.setSelectedItem(veiculo.getTipoDeRota());
            CadasVei_CB_tipoDeVeiculo.setSelectedItem(veiculo.getTipoDeVeiculo());
            CadasVei_CB_tipoDeCobranca.setSelectedItem(veiculo.getTipoDeCobranca());
            if(veiculo instanceof Onibus){
                CadasVei_CT_placa.setText(((Onibus)veiculo).getPlaca());
            }
            CadasVei_CT_capacidade.setText(String.valueOf(veiculo.getCapacidade()));
            CadasVei_CT_autonomia.setText(String.valueOf(veiculo.getAutonomia()));
        }
        else{
            exibirMsg("VEÍCULO NÃO ENCONTRADO");
        }
        
    }//GEN-LAST:event_CadasVei_P_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {

        java.awt.EventQueue.invokeLater(() -> {
            new TelaGestorDeFrota().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Alocar_P;
    private javax.swing.JPanel BuscarRelatorios_P;
    private javax.swing.JButton CadasEmVe_BT_atualizar;
    private javax.swing.JButton CadasEmVe_BT_buscar;
    private javax.swing.JButton CadasEmVe_BT_cadastrar;
    private javax.swing.JButton CadasEmVe_BT_descadastrar;
    private javax.swing.JButton CadasEmVe_BT_limpar;
    private javax.swing.JTextField CadasEmVe_BT_veiculoId;
    private javax.swing.JTextField CadasEmVe_CT_cpf;
    private javax.swing.JTextField CadasEmVe_CT_rotaId;
    private javax.swing.JButton CadasParada_BT_atualizar;
    private javax.swing.JButton CadasParada_BT_buscar;
    private javax.swing.JButton CadasParada_BT_cadastrar;
    private javax.swing.JButton CadasParada_BT_limpar;
    private javax.swing.JButton CadasParada_BT_remover;
    private javax.swing.JTextField CadasParada_CT_endereco;
    private javax.swing.JTextField CadasParada_CT_id;
    private javax.swing.JTextField CadasParada_CT_latitude;
    private javax.swing.JTextField CadasParada_CT_longitude;
    private javax.swing.JTextField CadasRota_CT_idParada;
    private javax.swing.JButton CadasVei_BT_cadastrar;
    private javax.swing.JButton CadasVei_BT_limpar;
    private javax.swing.JComboBox CadasVei_CB_rotas;
    private javax.swing.JComboBox CadasVei_CB_status;
    private javax.swing.JComboBox CadasVei_CB_tipoCombustivel;
    private javax.swing.JComboBox CadasVei_CB_tipoDeCobranca;
    private javax.swing.JComboBox CadasVei_CB_tipoDeRota;
    private javax.swing.JComboBox CadasVei_CB_tipoDeVeiculo;
    private javax.swing.JTextField CadasVei_CT_autonomia;
    private javax.swing.JTextField CadasVei_CT_capacidade;
    private javax.swing.JTextField CadasVei_CT_id;
    private javax.swing.JTextField CadasVei_CT_placa;
    private javax.swing.JButton CadasVei_P_atualizar;
    private javax.swing.JButton CadasVei_P_buscar;
    private javax.swing.JPanel CadasVei_P_id;
    private javax.swing.JPanel CadasVei_P_placa;
    private javax.swing.JButton CadasVei_P_remover;
    private javax.swing.JPanel CadastrarParada_P;
    private javax.swing.JPanel CadastrarRota_P;
    private javax.swing.JPanel CadastrarVeiculo_P;
    private javax.swing.JLabel IdParada;
    private javax.swing.JButton Pefil_BT_atualizar;
    private javax.swing.JButton Pefil_BT_limpar;
    private javax.swing.JButton Pefil_BT_sair;
    private javax.swing.JPasswordField Pefil_CS_senhaAntiga;
    private javax.swing.JPasswordField Pefil_CS_senhaNova;
    private javax.swing.JTextField Perfil_CT_cargaHoraria;
    private javax.swing.JTextField Perfil_CT_salario;
    private javax.swing.JTextField Perfil_CT_usuario;
    private javax.swing.JPanel Perfil_P;
    private javax.swing.JTextArea RelatoriosPorPe_AT_info;
    private javax.swing.JButton RelatoriosPorPe_BT_limpar;
    private javax.swing.JButton RelatoriosPorPe_BT_mostraRelatorio;
    private javax.swing.JComboBox RelatoriosPorPe_CB_tipoDeVeiculo;
    private javax.swing.JFormattedTextField RelatoriosPorPe_CTF_dataFinal;
    private javax.swing.JFormattedTextField RelatoriosPorPe_CTF_dataInicial;
    private javax.swing.JRadioButton RelatoriosPorPe_RB_funcionario;
    private javax.swing.JRadioButton RelatoriosPorPe_RB_veiculo;
    private javax.swing.JButton Relatorios_BT_balanco;
    private javax.swing.JButton Relatorios_BT_limpar;
    private javax.swing.JButton Relatorios_BT_mostrarRelatorio;
    private javax.swing.JComboBox Relatorios_CB_tipoDeVeiculos;
    private javax.swing.JTextField Relatorios_CT_idade;
    private javax.swing.JTextField Relatorios_CT_renda;
    private javax.swing.JTextField Relatorios_CT_sexo;
    private javax.swing.JPanel Relatorios_P;
    private javax.swing.JTextPane Relatorios_PT_info;
    private javax.swing.JRadioButton Relatorios_RB_funcionario;
    private javax.swing.JRadioButton Relatorios_RB_veiculo;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables
}
